# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  aphw-ddi-events:
    build:
      target: development
    image: aphw-ddi-events-development
    container_name: aphw-ddi-events-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      PACT_BROKER_URL: ${PACT_BROKER_URL:-notset}
      PACT_BROKER_USERNAME: ${PACT_BROKER_USERNAME:-notset}
      PACT_BROKER_PASSWORD: ${PACT_BROKER_PASSWORD:-notset}

  aphw-ddi-event-store-azurite:
    labels:
      com.docker.compose.pay.role: test
