# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  dangerous-dogs-index-events:
    build:
      target: development
    image: dangerous-dogs-index-events-development
    container_name: dangerous-dogs-index-events-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json

  dangerous-dogs-index-event-store-azurite:
    labels:
      com.docker.compose.pay.role: test
