# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  dangerous-dogs-index-events:
    build:
      target: development
    image: dangerous-dogs-index-events-development
    container_name: dangerous-dogs-index-events-development
    ports:
      - "3005:3000"
      - "9235:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  dangerous-dogs-index-event-store-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10080:10000"
      - "10081:10001"
      - "10082:10002"

volumes:
  azurite_data:
