services:
  aphw-ddi-events:
    build:
      context: .
      target: production
    image: aphw-ddi-events
    container_name: aphw-ddi-events
    depends_on:
      - aphw-ddi-event-store-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-events-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-aphw-ddi-events}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_SUBSCRIPTION_ADDRESS: ${EVENT_SUBSCRIPTION_ADDRESS:-aphw-ddi-event-hub}${MESSAGE_QUEUE_SUFFIX}
      ALERT_TOPIC_ADDRESS: ${ALERT_TOPIC_ADDRESS:-aphw-ddi-alert}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://aphw-ddi-event-store-azurite:10002/devstoreaccount1;
      AZURE_STORAGE_ACCOUNT_NAME: devstoreaccount1
      PORTAL_PUBLIC_KEY: ${PORTAL_PUBLIC_KEY}
      ENFORCEMENT_PUBLIC_KEY: ${ENFORCEMENT_PUBLIC_KEY}
      PERMITTED_DOMAINS: ${PERMITTED_DOMAINS}

  aphw-ddi-event-store-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose"
    labels:
      com.docker.compose.pay.role: aphw-ddi-event-store-azurite
