{{- include "ffc-helm-library.container-secret" (list . "dangerous-dogs-index-events.container-secret") -}}
{{- define "dangerous-dogs-index-events.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
