{{- include "ffc-helm-library.deployment" (list . "dangerous-dogs-index-events.deployment") -}}
{{- define "dangerous-dogs-index-events.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "dangerous-dogs-index-events.container") }}
{{- end -}}
